export const LEADER_BOARD_CONST = {
  LEADER_BOARD_PREFIX: 'LEADER_BOARD',
};

export const QUIZ_BATCH_SIZE = 10;
export const USER_SCORE_BATCH_SIZE = 500;
export const WAITING_FOR_INIT_LEADER_BOARD_QUEUE_LOCK =
  'WAITING_FOR_INIT_LEADER_BOARD_QUEUE_LOCK';
export const WAITING_FOR_INIT_LEADER_BOARD_QUEUE =
  'WAITED_FOR_INIT_LEADER_BOARD_QUEUE';
export const INITIALIZING_LEADER_BOARD_PREFIX =
  'INITIALIZING_LEADER_BOARD_PREFIX';
