version: '3.8'

services:
  flyway:
    container_name: flyway
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://db:5432/leaderboard -user=root -password=root -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./flyway/migrate:/flyway/sql
    depends_on:
      - db
    networks:
      - shared-network
  
  db:
    container_name: db
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      DATABASE_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - shared-network
      
  redis:
    container_name: redis
    image: redis:7.2.3-alpine3.18
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    networks:
      - shared-network

volumes:
  node_modules:
  dbdata:
  redisdata:

networks:
  shared-network:
    name: shared-network
